// <auto-generated />
using System;
using KHP.Dal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KHP.Dal.Migrations
{
    [DbContext(typeof(KHPDbContext))]
    [Migration("20240208155421_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KHP.Entities.Gida", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GidaTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kalori")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Porsiyon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Resim")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ID");

                    b.ToTable("Gidalar");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Ad = "Salata",
                            GidaTuru = "Yiyecek",
                            Kalori = 152m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 2,
                            Ad = "Kek",
                            GidaTuru = "Yiyecek",
                            Kalori = 357m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 3,
                            Ad = "Tost",
                            GidaTuru = "Yiyecek",
                            Kalori = 289m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 4,
                            Ad = "Pizza",
                            GidaTuru = "Yiyecek",
                            Kalori = 30m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 5,
                            Ad = "Makarna",
                            GidaTuru = "Meyve",
                            Kalori = 30m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 6,
                            Ad = "Burger",
                            GidaTuru = "Yiyecek",
                            Kalori = 300m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 7,
                            Ad = "Köfte",
                            GidaTuru = "Yiyecek",
                            Kalori = 320m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 8,
                            Ad = "Patates",
                            GidaTuru = "Yiyecek",
                            Kalori = 77m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 9,
                            Ad = "Soğan",
                            GidaTuru = "Yiyecek",
                            Kalori = 40m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 10,
                            Ad = "Kahve",
                            GidaTuru = "Icecek",
                            Kalori = 211m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 11,
                            Ad = "Çay",
                            GidaTuru = "Icecek",
                            Kalori = 110m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 12,
                            Ad = "Pankek",
                            GidaTuru = "Yiyecek",
                            Kalori = 352m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 13,
                            Ad = "Meyve Suyu",
                            GidaTuru = "Icecek",
                            Kalori = 190m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 14,
                            Ad = "Brownie",
                            GidaTuru = "Yiyecek",
                            Kalori = 250m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 15,
                            Ad = "Yoğurt",
                            GidaTuru = "Yiyecek",
                            Kalori = 59m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 16,
                            Ad = "Havuç",
                            GidaTuru = "Yiyecek",
                            Kalori = 95m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 17,
                            Ad = "Turp",
                            GidaTuru = "Yiyecek",
                            Kalori = 52m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 18,
                            Ad = "Kola",
                            GidaTuru = "İcecek",
                            Kalori = 178m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 19,
                            Ad = "Peynir",
                            GidaTuru = "Yiyecek",
                            Kalori = 328m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 20,
                            Ad = "Domates",
                            GidaTuru = "Yiyecek",
                            Kalori = 85m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 21,
                            Ad = "Zeytin",
                            GidaTuru = "Yiyecek",
                            Kalori = 105m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 22,
                            Ad = "Dondurma",
                            GidaTuru = "Yiyecek",
                            Kalori = 105m,
                            Porsiyon = 1m
                        },
                        new
                        {
                            ID = 23,
                            Ad = "ET",
                            GidaTuru = "Yiyecek",
                            Kalori = 350m,
                            Porsiyon = 1m
                        });
                });

            modelBuilder.Entity("KHP.Entities.Kullanici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cinsiyet")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("KHP.Entities.KullaniciGida", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("GidaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GidaTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kalori")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("OgunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("Porsiyon")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("KullaniciId");

                    b.ToTable("KullaniciGidalar");
                });

            modelBuilder.Entity("KHP.Entities.KullaniciGida", b =>
                {
                    b.HasOne("KHP.Entities.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });
#pragma warning restore 612, 618
        }
    }
}
